project:
  type: website

website:
  sidebar:
    style: docked
    title: "Stat 999"
    logo: assets/stat_bear.png
    contents:
      - href: index.qmd
        text: Home 
      - href: staff.qmd
        text: Staff
      - href: syllabus.qmd
        text: Syllabus
    footer: 
      <a href="license.qmd">License</a>
          

format:
  html:
    theme: cosmo
    css: assets/styles.css
    toc: true



